USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHECKTENLOP]    Script Date: 5/23/2022 6:20:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CHECKTENLOP]
@TLOP NVARCHAR(50)
AS 
IF EXISTS(SELECT TENLOP FROM DBO.LOP WHERE TENLOP = @TLOP)
	BEGIN
		SELECT 'SV' = 1 
	END
ELSE
IF EXISTS(SELECT TENLOP FROM LINK0.QLDSV_HTC.DBO.LOP WHERE TENLOP = @TLOP)
	BEGIN
		SELECT 'SV' = 2
	END
ELSE
	SELECT 'SV' = 0
GO


