USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSSV_DANGKY_LTC]    Script Date: 5/23/2022 6:23:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DSSV_DANGKY_LTC]
@NIENKHOA NCHAR(9),
@HOCKY INT,
@MONHOC NCHAR(10),
@NHOM INT

AS
	DECLARE @TENMH NVARCHAR(50),@MALTC INT, @PHAI NVARCHAR(10)
	SELECT @TENMH = TENMH FROM MONHOC WHERE MAMH = @MONHOC
	SELECT @MALTC = MALTC FROM LOPTINCHI 
			WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MONHOC AND NHOM = @NHOM

	
	SELECT STT = ROW_NUMBER() OVER(ORDER BY TEN, HO), DK.MASV, HO, TEN,CASE WHEN PHAI = 'FALSE' THEN N'Nam' ELSE N'Nữ' END AS PHAI , MALOP
	FROM (SELECT MASV FROM DANGKY WHERE MALTC=@MALTC AND HUYDANGKY = 'FALSE') DK
	INNER JOIN (SELECT MASV, HO, TEN, PHAI, MALOP FROM SINHVIEN) SV
	ON SV.MASV = DK.MASV
	ORDER BY TEN, HO


GO


