USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DANGKY_LTC]    Script Date: 5/23/2022 6:20:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DANGKY_LTC]
@MALTC INT, @MASV NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT * FROM DANGKY WHERE MALTC = @MALTC AND MASV = @MASV)
		BEGIN
			UPDATE DANGKY SET HUYDANGKY = 0 WHERE MALTC = @MALTC AND MASV = @MASV
		END
	ELSE
		BEGIN
			INSERT INTO DANGKY(MALTC,MASV)
			VALUES (@MALTC, @MASV)
		END
END
GO


