USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_LAYHOTENLOPSV]    Script Date: 5/23/2022 6:24:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_LAYHOTENLOPSV]
@MSV NCHAR(10) 
AS
DECLARE @TLOP NVARCHAR(50), @MLOP NCHAR(10), @HOTEN NVARCHAR(60)

		SELECT @HOTEN = HO + ' ' + TEN  , @MLOP=MALOP FROM SINHVIEN WHERE MASV = @MSV
		SELECT HOTEN = @HOTEN, MALOP = @MLOP, TENLOP FROM LOP WHERE @MLOP = MALOP

--IF EXISTS(SELECT HO + ' ' + TEN, MALOP FROM SINHVIEN WHERE MASV = @MSV)
--	BEGIN
		
--		SELECT @HOTEN = HO + ' ' + TEN  , @MLOP=MALOP FROM SINHVIEN WHERE MASV = @MSV
--		SELECT HOTEN = @HOTEN, MALOP = @MLOP, TENLOP FROM LOP WHERE @MLOP = MALOP
--	END
--ELSE
--IF EXISTS(SELECT HO + ' ' + TEN, MALOP FROM LINK0.QLDSV_HTC.DBO.SINHVIEN WHERE MASV = @MSV)
--	BEGIN
--		SELECT @HOTEN = HO + ' ' + TEN,@MLOP = MALOP FROM LINK0.QLDSV_HTC.DBO.SINHVIEN WHERE MASV = @MSV
--		SELECT HOTEN = @HOTEN,MALOP = @MLOP,TENLOP FROM LINK0.QLDSV_HTC.DBO.LOP WHERE MALOP = @MLOP
--	END





GO


