USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CTHOCPHI]    Script Date: 5/22/2022 5:08:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CTHOCPHI]
@MASV NCHAR(10),
@NIENKHOA NCHAR(9),
@HOCKY INT

AS
SELECT NGAYDONG,SOTIENDONG FROM CT_DONGHOCPHI WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MASV = @MASV
GO

