USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSHPLOP]    Script Date: 5/22/2022 5:09:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DSHPLOP]
	@MALOP NCHAR(10),
	@NIENKHOA NCHAR(9),
	@HOCKY INT
AS
BEGIN
	SELECT HO + ' ' + TEN AS N'Họ và Tên',HOCPHI AS N'Học phí',TONGTIENDONG AS N'Tổng số tiền đã đóng'	FROM
	(SELECT  MASV,HO,TEN  FROM SINHVIEN 
	WHERE MALOP = @MALOP AND DANGHIHOC = 'FALSE') HOTEN
	INNER JOIN 
	(SELECT HOCPHI.MASV,HOCPHI.NIENKHOA,HOCPHI.HOCKY,HOCPHI.HOCPHI,TONGTIENDONG = SUM (SOTIENDONG) FROM HOCPHI,CT_DONGHOCPHI
	WHERE HOCPHI.MASV = CT_DONGHOCPHI.MASV AND CT_DONGHOCPHI.NIENKHOA = @NIENKHOA AND CT_DONGHOCPHI.HOCKY = @HOCKY
	AND HOCPHI.NIENKHOA = @NIENKHOA AND HOCPHI.HOCKY = @HOCKY
	GROUP BY HOCPHI.MASV,HOCPHI.NIENKHOA,HOCPHI.HOCKY,HOCPHI.HOCPHI) HP
	ON HOTEN.MASV = HP.MASV
END
GO

