USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSHOCPHI]    Script Date: 5/22/2022 5:09:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DSHOCPHI]
@MASV NCHAR(10)
AS
BEGIN
	SELECT  HP.NIENKHOA AS N'Niên khóa',HP.HOCKY AS N'Học kỳ', HP.HOCPHI AS N'Học phí', ISNULL(TONGTIENDONG,0) AS N'Tổng số tiền đóng'
	FROM ((SELECT NIENKHOA, HOCKY,HOCPHI FROM HOCPHI WHERE MASV = @MASV) HP
	LEFT JOIN 
	(SELECT NIENKHOA, HOCKY,TONGTIENDONG=SUM(CTDHP.SOTIENDONG) FROM CT_DONGHOCPHI CTDHP WHERE MASV = @MASV 
	GROUP BY CTDHP.NIENKHOA, CTDHP.HOCKY) CTDHP 
	ON HP.NIENKHOA = CTDHP.NIENKHOA  AND HP.HOCKY = CTDHP.HOCKY)
END
GO

