USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DIEMTONGKET]    Script Date: 5/22/2022 5:09:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DIEMTONGKET]
@MALOP NVARCHAR(15)
AS
BEGIN
	SELECT SV.MASV, HOTEN,TENMH, DIEM= (DIEM_CC*0.1+ DIEM_GK*0.3+ DIEM_CK*0.6)
		FROM (SELECT MASV, MALTC, DIEM_CC, DIEM_GK,DIEM_CK FROM DANGKY 
		WHERE HUYDANGKY = 'FALSE') DK,
		(SELECT MASV,HOTEN = HO+ ' ' + TEN FROM SINHVIEN WHERE MALOP= @MALOP AND DANGHIHOC  = 'FALSE') SV,
		(SELECT MALTC, MAMH FROM LOPTINCHI) LTC, MONHOC
		WHERE DK.MASV = SV.MASV AND DK.MALTC = LTC.MALTC AND LTC.MAMH = MONHOC.MAMH
END
GO

