USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DIEMTC]    Script Date: 5/22/2022 5:09:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DIEMTC]
	@MALTC NCHAR(10)
AS
BEGIN
	SELECT DANGKY.MASV,HO +' '+TEN AS HOTENSV,DIEM_CC,DIEM_GK,DIEM_CK 
		FROM DANGKY,SINHVIEN 
		WHERE DANGKY.MASV = SINHVIEN.MASV AND MALTC = @MALTC AND DANGHIHOC = 'FALSE'
END
GO

