USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_LTC]    Script Date: 5/22/2022 5:10:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_LTC] 
	@NK NCHAR(9),
	@HK INT
AS
BEGIN
	SELECT MALTC,TENMH,NHOM,HO +' '+ TEN AS HOTEN 
		FROM LOPTINCHI,MONHOC,GIANGVIEN 
		WHERE LOPTINCHI.MAMH = MONHOC.MAMH AND LOPTINCHI.MAGV = GIANGVIEN.MAGV AND HOCKY = @HK AND NIENKHOA = @NK
END
GO

