USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_NIENKHOA]    Script Date: 5/22/2022 5:10:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_NIENKHOA]
AS
SELECT NIENKHOA FROM LOPTINCHI GROUP BY NIENKHOA
GO

