USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHECKTENLOP]    Script Date: 3/24/2022 3:10:15 PM ******/


CREATE PROC [dbo].[SP_CHECKTENLOP]
@TLOP NVARCHAR(50)
AS 
IF EXISTS(SELECT TENLOP FROM DBO.LOP WHERE TENLOP = @TLOP)
	BEGIN
		SELECT 'SV' = 1 
	END
ELSE
IF EXISTS(SELECT TENLOP FROM LINK0.QLDSV_HTC.DBO.LOP WHERE TENLOP = @TLOP)
	BEGIN
		SELECT 'SV' = 2
	END
ELSE
	SELECT 'SV' = 0
GO


