USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DANGNHAP]    Script Date: 3/24/2022 3:10:38 PM ******/

--exec [dbo].[SP_DANGNHAP] 'GV'

CREATE PROC [dbo].[SP_DANGNHAP]
@TENLOGIN NVARCHAR (50)
AS

DECLARE @TENUSER NVARCHAR(50)
SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
 

 declare @TENNHOM NVARCHAR(50)
 SELECT @TENNHOM = NAME  FROM sys.sysusers 
   WHERE UID = (SELECT GROUPUID 
                 FROM SYS.SYSMEMBERS 
                   WHERE MEMBERUID= (SELECT UID FROM sys.sysusers 
                                      WHERE NAME=@TENUSER))
IF @TENNHOM ='SV'
BEGIN
SELECT USERNAME = @TENUSER, 
  HOTEN = (SELECT HO+ ' '+ TEN FROM SINHVIEN  WHERE MASV = @TENUSER ),
  TENNHOM=@TENNHOM
	
END
ELSE
BEGIN
	SELECT USERNAME = @TENUSER, 
  HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN  WHERE MAGV = @TENUSER ),
  TENNHOM=@TENNHOM
END

GO


