USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSLTCDADANGKY]    Script Date: 4/23/2022 1:51:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DSLTCDADANGKY] 
@MSV NCHAR(10) , @NIENKHOA NVARCHAR(11), @HOCKY INT 
AS 

BEGIN
	SELECT ROW_NUMBER() over(ORDER BY MH.TENMH, LTC.NHOM) STT,LTC.MAMH,TENMH,NIENKHOA,HOCKY,NHOM, LTC.MALTC
	FROM (SELECT MALTC FROM DANGKY WHERE MASV = @MSV AND HUYDANGKY = 0) DS
	INNER JOIN (SELECT MALTC,MAMH,NIENKHOA,HOCKY,NHOM FROM LOPTINCHI) LTC 
		ON DS.MALTC = LTC.MALTC
	INNER JOIN (SELECT MAMH,TENMH FROM MONHOC) MH 
		ON LTC.MAMH = MH.MAMH
	WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY 
END

GO


