USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DANGNHAP_SV]    Script Date: 5/23/2022 6:21:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_DANGNHAP_SV]
@MASV NCHAR(10),
@MK NVARCHAR(40)

AS
DECLARE @HOTEN NVARCHAR(60), @DANGHIHOC BIT
	SET @HOTEN = ''
	SELECT @HOTEN = HO+ ' '+ TEN, @DANGHIHOC = DANGHIHOC FROM SINHVIEN  WHERE MASV = @MASV AND PASSWORD = @MK
	IF @HOTEN = ''
		RETURN NULL
	SELECT USERNAME = @MASV, 
			HOTEN = @HOTEN,
			TENNHOM='SINH VIEN',
			DANGHIHOC = @DANGHIHOC -- LAY FEILD DA NGHI HOC DE XET SINHVIEN NAY CON QUYEN DANG NHAP NUA KO
GO


