USE [QLDSV_HTC]
GO

/****** Object:  View [dbo].[V_LAY_NIENKHOA]    Script Date: 5/23/2022 6:36:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_LAY_NIENKHOA]
AS
	SELECT DISTINCT NIENKHOA FROM LOPTINCHI

GO

