USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_BDMH]    Script Date: 5/23/2022 6:30:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_BDMH] @NIENKHOA NCHAR(9), @HOCKY INT, @MONHOC NVARCHAR(50), @NHOM INT
AS
BEGIN 
	DECLARE @MAMH NCHAR(10), @MALTC NCHAR(10)
	SELECT @MAMH = MAMH
	FROM MONHOC MH
	WHERE MH.TENMH = @MONHOC

	SELECT @MALTC = MALTC
	FROM LOPTINCHI LTC
	WHERE MAMH = @MAMH AND NIENKHOA = @NIENKHOA AND NHOM = @NHOM AND HOCKY = @HOCKY

	SELECT MASV, DIEM_CC, DIEM_GK, DIEM_CK
	INTO #B1
	FROM DANGKY DK
	WHERE MALTC = @MALTC

	SELECT MASV
	INTO #B2
	FROM DANGKY DK
	WHERE MALTC = @MALTC

	SELECT #B2.MASV, HO, TEN
	INTO #B3
	FROM SINHVIEN SV INNER JOIN #B2 ON SV.MASV = #B2.MASV
	SET NOCOUNT ON
	  IF 1=0 BEGIN  
        SET FMTONLY OFF  
    END  
	SELECT #B1.MASV, #B3.HO, #B3.TEN, DIEM_CC, DIEM_GK, DIEM_CK
	FROM #B1 INNER JOIN #B3 ON #B1.MASV = #B3.MASV
END
GO


