USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CHECKTENMH]    Script Date: 5/23/2022 6:31:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CHECKTENMH]
@TENMH NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM MONHOC WHERE TENMH = @TENMH)
		SELECT KT = 1
	ELSE 
		IF EXISTS(SELECT * FROM LINK0.QLDSV_HTC.DBO.MONHOC WHERE TENMH = @TENMH)	
			SELECT KT = 1
		ELSE
			SELECT KT = 0
END
GO


