USE [QLDSV_HTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_PD]    Script Date: 5/23/2022 6:33:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_PD]
@MASV NCHAR(10)
AS
BEGIN
	SELECT DK.MALTC, DIEM_HM = DIEM_CC*0.1 + DIEM_GK*0.3 + DIEM_CK*0.6
	INTO #B1
	FROM DANGKY DK
	WHERE DK.MASV = @MASV
	
	SELECT DK.MALTC
	INTO #B2
	FROM DANGKY DK
	WHERE DK.MASV = @MASV

	SELECT LTC.MALTC, LTC.MAMH
	INTO #B3
	FROM LOPTINCHI LTC RIGHT JOIN #B2 ON LTC.MALTC = #B2.MALTC AND LTC.HUYLOP = 0
	
	SELECT #B3.MALTC, MH.TENMH
	INTO #B4
	FROM #B3 INNER JOIN MONHOC MH ON MH.MAMH = #B3.MAMH
	
	SELECT #B4.TENMH, DIEM_HM = MAX(#B1.DIEM_HM)
	FROM #B1 INNER JOIN #B4 ON #B1.MALTC = #B4.MALTC
	GROUP BY #B4.TENMH
	
END
GO


